// FOIA OS v2 — ActivityEngine
// Pure business logic for investigation timeline events.
// Activities are generated by engines — never created manually or on read.

import { DomainEngine } from './engine';

const ACTION_TYPES = {
  INVESTIGATION_CREATED: 'investigation_created',
  INVESTIGATION_STAGE_CHANGED: 'investigation_stage_changed',
  EVIDENCE_STAGE_CHANGED: 'evidence_stage_changed',
  EVIDENCE_ASSIGNED: 'evidence_assigned',
  REQUEST_SENT: 'request_sent',
  REQUEST_STATUS_CHANGED: 'request_status_changed',
  COMMUNICATION_SENT: 'communication_sent',
  COMMUNICATION_RECEIVED: 'communication_received',
  DOCUMENT_UPLOADED: 'document_uploaded',
  DOCUMENT_VERIFIED: 'document_verified',
  DOCUMENT_LINKED: 'document_linked',
  TEAM_MEMBER_ADDED: 'team_member_added',
  TEAM_MEMBER_REMOVED: 'team_member_removed',
  PRODUCTION_STAGE_CHANGED: 'production_stage_changed',
  PRODUCTION_DELIVERED: 'production_delivered',
};

const ACTION_LABELS = {
  investigation_created: { ar: 'تم إنشاء التحقيق', en: 'Investigation created' },
  investigation_stage_changed: { ar: 'تغيرت مرحلة التحقيق', en: 'Investigation stage changed' },
  evidence_stage_changed: { ar: 'تغيرت حالة الدليل', en: 'Evidence stage changed' },
  evidence_assigned: { ar: 'تم تعيين الدليل', en: 'Evidence assigned' },
  request_sent: { ar: 'أرسل طلب إلى جهة', en: 'Request sent to agency' },
  request_status_changed: { ar: 'تغيرت حالة الطلب', en: 'Request status changed' },
  communication_sent: { ar: 'بريد صادر', en: 'Outgoing email' },
  communication_received: { ar: 'بريد وارد', en: 'Incoming email' },
  document_uploaded: { ar: 'رفع ملف', en: 'File uploaded' },
  document_verified: { ar: 'توثيق ملف', en: 'Document verified' },
  document_linked: { ar: 'ربط ملف بدليل', en: 'Document linked to evidence' },
  team_member_added: { ar: 'إضافة عضو', en: 'Team member added' },
  team_member_removed: { ar: 'إزالة عضو', en: 'Team member removed' },
  production_stage_changed: { ar: 'تغيرت مرحلة الإنتاج', en: 'Production stage changed' },
  production_delivered: { ar: 'تم تسليم الإنتاج', en: 'Production delivered' },
};

class ActivityEngineClass extends DomainEngine {
  constructor() {
    super('ActivityEngine');
    this._pending = [];
  }

  getActionTypes() { return { ...ACTION_TYPES }; }

  getLabel(type, lang = 'ar') {
    return ACTION_LABELS[type]?.[lang] || type;
  }

  record(action = {}) {
    const entry = {
      id: this._generateId(),
      type: action.type || 'unknown',
      title: this.getLabel(action.type) + (action.detail ? `: ${action.detail}` : ''),
      investigationId: action.investigationId,
      evidenceId: action.evidenceId || null,
      requestId: action.requestId || null,
      documentId: action.documentId || null,
      userId: action.userId,
      userName: action.userName || 'System',
      timestamp: new Date().toISOString(),
      metadata: action.metadata || {},
    };
    this._pending.push(entry);
    return entry;
  }

  flush() {
    const items = [...this._pending];
    this._pending = [];
    return items;
  }

  createTimeline(activities = []) {
    return activities
      .sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp))
      .map(a => ({
        id: a.id,
        title: a.title,
        description: `${a.userName} - ${new Date(a.timestamp).toLocaleString('ar-SA')}`,
        timestamp: a.timestamp,
        type: a.type,
        icon: this._getIcon(a.type),
      }));
  }

  _generateId() {
    return `act_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`;
  }

  _getIcon(type) {
    const ICONS = {
      investigation_created: '📁',
      investigation_stage_changed: '🔄',
      evidence_stage_changed: '📋',
      request_sent: '📨',
      communication_sent: '📤',
      communication_received: '📥',
      document_uploaded: '📄',
      team_member_added: '👤',
      production_delivered: '✅',
    };
    return ICONS[type] || '📌';
  }

  // Static helpers for creating common activity entries
  static stageChange(investigationId, from, to, userId, userName) {
    return {
      type: ACTION_TYPES.INVESTIGATION_STAGE_CHANGED,
      investigationId,
      detail: `${from} → ${to}`,
      userId,
      userName,
    };
  }

  static evidenceStageChange(evidenceId, recordType, from, to, userId, userName) {
    return {
      type: ACTION_TYPES.EVIDENCE_STAGE_CHANGED,
      investigationId: null,
      evidenceId,
      detail: `${recordType}: ${from} → ${to}`,
      userId,
      userName,
    };
  }
}

export const ActivityEngine = new ActivityEngineClass();
